config/routes.rb
Rails.application.routes.draw do
  get 'ask', to: 'questions#ask', as: :ask
  # post 'ask', to: 'questions#ask'
  get 'answer', to: 'questions#answer', as: :answer
  # get 'answer/:id', to: 'questions#show'

  root to: 'questions#home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def ask
  end

  def answer
    @question = params[:question]
    @name = params[:name]

    if @question == 'I am going to work'
      @answer = 'Great!'
    elsif @question.include?('?')
      @answer = 'Silly question, get dressed and go to work!'
    else
      @answer = "I don't care, get dressed and go to work!"
    end
  end

  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsStupidCoaching</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/questions/answer.html.erb
<h1>Questions#answer</h1>
<h1>You asked: <%= @question %></h1>
<h2>Your coach answered: <%= @answer %></h2>

<%= link_to "BACK", "/ask" %>

app/views/questions/ask.html.erb
<h1>I'm your coach.</h1>
<h2>Ask me something!</h2>

<form action="/answer" method="get">
  <label for="question">Question</label>
  <input type="text" name="question">

<!--   <label for="name">What's your name</label>
  <input type="text" name="name"> -->

  <input type="submit">

</form>

<!-- <form action="/ask" method="post">
  <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
  <input type="text" name="test_input">
  <input type="submit">
</form>

<%= link_to 'first answer', answer_path(@answer)  %> -->